"""Generate parameterised track TOML files used by the racing demos.

Run this script directly to regenerate `figure8.toml`:

    python examples/tracks/_generate.py

The TOML produced here is the runtime source of truth — the demo loads
the TOML, not this script. Re-run only if you want to change the shape
or the sample count.
"""
from __future__ import annotations

import math
from pathlib import Path
from typing import Iterable, List, Tuple


Waypoint = Tuple[float, float]


def lemniscate_bernoulli(a: float = 1.2, n: int = 60) -> List[Waypoint]:
    """Bernoulli lemniscate (∞-shape) sampled uniformly in parameter t.

    Parametric form:
        x(t) = a · cos(t) / (1 + sin²(t))
        y(t) = a · sin(t) · cos(t) / (1 + sin²(t))

    `a` is the half-width (m). The curve crosses itself at the origin
    twice per loop. Sampling t at (i + ½)·2π/n avoids placing two
    waypoints exactly on top of the crossing.
    """
    pts: List[Waypoint] = []
    for i in range(n):
        t = (i + 0.5) * 2.0 * math.pi / n
        s = math.sin(t)
        c = math.cos(t)
        denom = 1.0 + s * s
        x = a * c / denom
        y = a * s * c / denom
        pts.append((x, y))
    return pts


def write_toml(path: Path, name: str, waypoints: Iterable[Waypoint],
               closed: bool = True) -> None:
    pts = list(waypoints)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f'# Auto-generated by examples/tracks/_generate.py. Edit there.\n')
        f.write(f'name = "{name}"\n')
        f.write(f'closed = {"true" if closed else "false"}\n')
        f.write(f'waypoints = [\n')
        for x, y in pts:
            f.write(f'    [{x:.6f}, {y:.6f}],\n')
        f.write(f']\n')


def main() -> None:
    here = Path(__file__).parent
    pts = lemniscate_bernoulli(a=1.2, n=60)
    out = here / "figure8.toml"
    write_toml(out, name="figure-8", waypoints=pts, closed=True)
    # quick stats for sanity
    total = 0.0
    for i in range(len(pts)):
        x0, y0 = pts[i]
        x1, y1 = pts[(i + 1) % len(pts)]
        total += math.hypot(x1 - x0, y1 - y0)
    print(f"Wrote {len(pts)} waypoints to {out}")
    print(f"Approximate perimeter: {total:.3f} m")


if __name__ == "__main__":
    main()
